export const VIDEO_CATEGORIES = [
  { id: "all", label: "All", image: "/img/cat/video/All.jpg" },
  { id: "music", label: "Music", image: "/img/cat/video/Music.png" },
  { id: "gaming", label: "Gaming", image: "/img/cat/video/Gaming.png" },
  { id: "sports", label: "Sports", image: "/img/cat/video/Sports.png" },
  { id: "news", label: "News", image: "/img/cat/video/News.png" },
  { id: "entertainment", label: "Entertainment", image: "/img/cat/video/Entertainment.png" },
  { id: "education", label: "Education", image: "/img/cat/video/Education.png" },
  { id: "tech", label: "Tech", image: "/img/cat/video/Tech.jpg" },
  { id: "comedy", label: "Comedy", image: "/img/cat/video/Comedy.png" },
  { id: "travel", label: "Travel", image: "/img/cat/video/Travel.jpg" },
];

export const VIDEO_FILTERS = [
  { id: "all", label: "All" },
  { id: "shorts", label: "Shorts" },
  { id: "trending", label: "Trending" },
  { id: "latest", label: "Latest" },
  { id: "mix", label: "Mix" },
];

const VIDEO_CATALOG = [
  {
    id: "agt-2026",
    title: "America's Got Talent 2026",
    channel: "Strug Uploads",
    views: "50 views",
    ago: "18d",
    duration: "67:30",
    category: "entertainment",
    filterTags: ["all", "trending", "latest"],
    thumbnail: "/img/cat/video/Entertainment.png",
    accent: "from-[#2c0c0c] via-[#6a1625] to-[#e6a14d]",
    featured: true,
  },
  {
    id: "league-of-legends",
    title: "League Of Legends",
    channel: "Strug Uploads",
    views: "20 views",
    ago: "25d",
    duration: "5:31",
    category: "gaming",
    filterTags: ["all", "trending", "mix"],
    thumbnail: "/img/cat/video/Gaming.png",
    accent: "from-[#071325] via-[#0a3158] to-[#41a3ff]",
  },
  {
    id: "star-trek",
    title: "Star Trek",
    channel: "Strug Uploads",
    views: "18 views",
    ago: "25d",
    duration: "18:06",
    category: "tech",
    filterTags: ["all", "latest", "mix"],
    thumbnail: "/img/cat/video/Tech.jpg",
    accent: "from-[#050812] via-[#121b30] to-[#454f70]",
  },
  {
    id: "movie-recaps",
    title: "Movie recaps",
    channel: "Strug Uploads",
    views: "16 views",
    ago: "25d",
    duration: "32:30",
    category: "comedy",
    filterTags: ["all", "latest", "mix"],
    thumbnail: "/img/cat/video/Comedy.png",
    accent: "from-[#0e0e14] via-[#21212a] to-[#53473b]",
  },
  {
    id: "blood-saint",
    title: "Blood Saint",
    channel: "Strug Uploads",
    views: "12 views",
    ago: "17d",
    duration: "3:44",
    category: "music",
    filterTags: ["all", "mix", "shorts"],
    thumbnail: "/img/cat/video/Music.png",
    accent: "from-[#2c1f1c] via-[#855537] to-[#f1ce8d]",
    isShort: true,
  },
  {
    id: "future-classroom",
    title: "Future Classroom",
    channel: "Strug Learning",
    views: "33 views",
    ago: "6d",
    duration: "12:18",
    category: "education",
    filterTags: ["all", "education", "latest"],
    thumbnail: "/img/cat/video/Education.png",
    accent: "from-[#0a1d23] via-[#11606c] to-[#a2f0ff]",
  },
  {
    id: "night-news-roundup",
    title: "Night News Roundup",
    channel: "Daily Strug",
    views: "84 views",
    ago: "3d",
    duration: "9:52",
    category: "news",
    filterTags: ["all", "trending", "latest"],
    thumbnail: "/img/cat/video/News.png",
    accent: "from-[#0f141c] via-[#2f445a] to-[#9fb4d2]",
  },
  {
    id: "travel-diaries",
    title: "Travel Diaries",
    channel: "Roam With Strug",
    views: "28 views",
    ago: "11d",
    duration: "14:02",
    category: "travel",
    filterTags: ["all", "mix", "latest"],
    thumbnail: "/img/cat/video/Travel.jpg",
    accent: "from-[#102421] via-[#2f6d64] to-[#d4d2a7]",
  },
];

export async function getVideosCatalog() {
  return VIDEO_CATALOG;
}
